# Generated by Django 5.1.1 on 2024-11-05 09:18

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_ad_category_ad_management_currentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='invoice-documents/', validators=[app1.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service_request', 'Service Request'), ('dealer_payment', 'Dealer Payment'), ('provider_payment', 'Service Provider Payment'), ('service_registration', 'service_registration'), ('Ads', 'Ads'), ('lead_purchase', 'lead_purchase'), ('others', 'others')], max_length=20),
        ),
    ]
