# Generated by Django 5.1.1 on 2024-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_user_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(max_length=20),
        ),
    ]
