# Generated by Django 5.1.1 on 2024-11-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_user_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentlocation',
            old_name='city',
            new_name='place',
        ),
    ]
