# Generated by Django 5.1.1 on 2024-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_city_currentlocation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
